version: '3.8'

services:
  # Frontend (development with hot reload)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_WS_URL=ws://localhost:3001
    networks:
      - agent-charlie-dev

  # Backend (development)
  backend-dev:
    build:
      context: ../agent-charlie-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ../agent-charlie-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=database-dev
      - DB_PORT=5432
    depends_on:
      - database-dev
      - redis-dev
    networks:
      - agent-charlie-dev

  # Development Database
  database-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=agent_charlie_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - agent-charlie-dev

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - agent-charlie-dev

networks:
  agent-charlie-dev:
    driver: bridge

volumes:
  postgres-dev-data: